// Pure formatter: GenerationResult -> a review-ready Markdown report.
// Kept free of the vscode API so it can be unit-tested in plain Node.

import type { GenerationResult } from "./api";

function bullets(items: string[]): string {
  return items.length ? items.map((i) => `- ${i}`).join("\n") : "_(none)_";
}

export function renderReport(result: GenerationResult): string {
  const { requirement: req, coverage, test_cases: cases } = result;
  const lines: string[] = [];

  lines.push(`# Test Cases — ${req.feature}`, "", "> Generated by TestCasePilot", "");

  if (req.user_story) {
    lines.push(`**User story:** ${req.user_story}`, "");
  }

  lines.push("## Business Rules", bullets(req.business_rules), "");
  lines.push("## Risks", bullets(req.risks), "");
  lines.push(
    "## Coverage",
    "**Covered:**",
    bullets(coverage.covered),
    "",
    "**Gaps:**",
    bullets(coverage.gaps),
    ""
  );

  lines.push(`## Test Cases (${cases.length})`, "");
  if (cases.length === 0) {
    lines.push("_No test cases were generated._", "");
  } else {
    cases.forEach((c, index) => {
      lines.push(`### ${index + 1}. ${c.title}  \`${c.type} · ${c.priority}\``);
      if (c.covers) {
        lines.push(`_Covers:_ ${c.covers}`);
      }
      lines.push("", "**Steps:**");
      c.steps.forEach((step, j) => lines.push(`${j + 1}. ${step}`));
      lines.push("", `**Expected:** ${c.expected_result}`, "");
    });
  }

  if (req.notes.length) {
    lines.push("---", "## Notes", bullets(req.notes), "");
  }

  return lines.join("\n");
}
