"""Deterministic Playwright spec generation from generated test cases.

Turns review-ready TestCases into a runnable Playwright spec SKELETON: each case
becomes a `test(...)` whose steps and expected result are preserved as guiding
comments, with a `test.fixme()` body for the QA engineer to implement. This is a
pure template — NO LLM — so it is fast and deterministic. Codegen lives in the
backend (per the architecture: the extension stays a thin client and only sends
the cases it already has).
"""

from __future__ import annotations

import re

from app.models import TestCase


def _slug(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.strip().lower()).strip("-")
    return slug or "requirement"


def _clean(text: str) -> str:
    """Collapse whitespace/newlines so a value is safe on a single comment line."""
    return " ".join(text.split())


def _esc(text: str) -> str:
    """Escape a string for embedding inside a single-quoted JS string literal."""
    return _clean(text).replace("\\", "\\\\").replace("'", "\\'")


def spec_filename(feature: str) -> str:
    return f"{_slug(feature)}.spec.ts"


def render_playwright_spec(feature: str, cases: list[TestCase]) -> str:
    """Render a Playwright spec skeleton for the given feature + test cases."""
    lines: list[str] = [
        "import { test, expect } from '@playwright/test';",
        "",
        f"// Auto-generated by TestCasePilot from feature: {_clean(feature)}",
        "// These are SCAFFOLDS — implement the steps and replace test.fixme().",
        "",
        f"test.describe('{_esc(feature)}', () => {{",
    ]

    if not cases:
        lines.append("  // No test cases were provided.")

    for case in cases:
        lines.append("")
        lines.append(f"  // [{_clean(case.type)} | {_clean(case.priority)}] "
                     f"covers: {_clean(case.covers) or 'n/a'}")
        lines.append(f"  test('{_esc(case.title)}', async ({{ page }}) => {{")
        if case.steps:
            lines.append("    // Steps:")
            for index, step in enumerate(case.steps, start=1):
                lines.append(f"    // {index}. {_clean(step)}")
        if case.expected_result:
            lines.append(f"    // Expected: {_clean(case.expected_result)}")
        lines.append("    // TODO: implement the steps above and assert the expected result.")
        lines.append("    test.fixme();")
        lines.append("  });")

    lines.append("})")
    lines.append("")
    return "\n".join(lines)
